In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('SOLUSDT_1m_012024_062025.csv')
# data = data[['open_time','open','high','low','close','volume']]
data = data.rename(columns = {'open_time':'timestamp'})
data.head()

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
0,2024-01-01 08:00:00+08:00,101.775,101.863,101.600,101.757,20309.0,2024-01-01 08:00:59.999000+08:00,2066106.213,2705,10358.0,1053808.762,0
1,2024-01-01 08:01:00+08:00,101.757,101.988,101.757,101.946,16508.0,2024-01-01 08:01:59.999000+08:00,1681452.106,2314,9771.0,995286.919,0
2,2024-01-01 08:02:00+08:00,101.946,102.192,101.913,102.190,21377.0,2024-01-01 08:02:59.999000+08:00,2181889.496,2642,14221.0,1451514.051,0
3,2024-01-01 08:03:00+08:00,102.189,102.391,102.082,102.313,68179.0,2024-01-01 08:03:59.999000+08:00,6970597.656,5838,34591.0,3537161.329,0
4,2024-01-01 08:04:00+08:00,102.313,102.487,102.260,102.356,20508.0,2024-01-01 08:04:59.999000+08:00,2099606.969,2647,12800.0,1310611.116,0

In [5]:
data.to_csv('SOLUSDT_1m_012024_062025_cleaned.csv')

In [6]:
june = pd.to_datetime('2025-06-01T00:00:00+08:00')
data['timestamp'] = pd.to_datetime(data['timestamp'])
june2025 = data[data['timestamp'] >= june]
june2025 = june2025.set_index('timestamp')
june2025.head()

,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
timestamp,,,,,,,,,,,
2025-06-01 00:00:00+08:00,155.51,155.52,155.34,155.34,8484.16,2025-06-01 00:00:59.999000+08:00,1.318721e+06,1348,2017.35,313595.8774,0
2025-06-01 00:01:00+08:00,155.33,155.42,155.10,155.18,19357.54,2025-06-01 00:01:59.999000+08:00,3.005880e+06,2318,5078.99,788796.5234,0
2025-06-01 00:02:00+08:00,155.17,155.29,155.07,155.26,18795.83,2025-06-01 00:02:59.999000+08:00,2.916241e+06,2039,6221.09,965343.2624,0
2025-06-01 00:03:00+08:00,155.26,155.26,155.14,155.19,8742.14,2025-06-01 00:03:59.999000+08:00,1.356627e+06,1438,3055.42,474131.5587,0
2025-06-01 00:04:00+08:00,155.18,155.22,155.10,155.19,6042.44,2025-06-01 00:04:59.999000+08:00,9.375354e+05,1166,2475.14,384053.8429,0

In [7]:
from modules.strategy import simulate_strategy
from modules.indicators import compute_indicators

params = {'sl_pct': 0.01, 'rsi_period': 7, 'bb_std': 2.0, 'sma_period': 30, 'breakeven_buffer': 0.05, 'cooldown_after_loss': True, 'max_concurrent_trades': 2}
june2025_ind = compute_indicators(june2025.copy(), params)
june_trades = simulate_strategy(june2025_ind, params)

In [8]:
junetrades = pd.DataFrame(june_trades) 
junetrades.to_csv('june_trades.csv')

In [9]:
june2025_ind

,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore,rsi,bb_upper,bb_lower,sma_tp,minute,is_5min_close
timestamp,,,,,,,,,,,,,,,,,
2025-06-01 00:00:00+08:00,155.51,155.52,155.34,155.34,8484.16,2025-06-01 00:00:59.999000+08:00,1.318721e+06,1348,2017.35,3.135959e+05,0,NaN,NaN,NaN,NaN,2025-06-01 00:00:00+08:00,True
2025-06-01 00:01:00+08:00,155.33,155.42,155.10,155.18,19357.54,2025-06-01 00:01:59.999000+08:00,3.005880e+06,2318,5078.99,7.887965e+05,0,NaN,NaN,NaN,NaN,2025-06-01 00:01:00+08:00,False
2025-06-01 00:02:00+08:00,155.17,155.29,155.07,155.26,18795.83,2025-06-01 00:02:59.999000+08:00,2.916241e+06,2039,6221.09,9.653433e+05,0,NaN,NaN,NaN,NaN,2025-06-01 00:02:00+08:00,False
2025-06-01 00:03:00+08:00,155.26,155.26,155.14,155.19,8742.14,2025-06-01 00:03:59.999000+08:00,1.356627e+06,1438,3055.42,4.741316e+05,0,NaN,NaN,NaN,NaN,2025-06-01 00:03:00+08:00,False
2025-06-01 00:04:00+08:00,155.18,155.22,155.10,155.19,6042.44,2025-06-01 00:04:59.999000+08:00,9.375354e+05,1166,2475.14,3.840538e+05,0,NaN,NaN,NaN,NaN,2025-06-01 00:04:00+08:00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-07-01 07:55:00+08:00,154.63,154.64,154.58,154.61,9136.53,2025-07-01 07:55:59.999000+08:00,1.412666e+06,881,3347.05,5.174942e+05,0,32.492389,156.278024,154.497309,155.387667,2025-07-01 07:55:00+08:00,True
2025-07-01 07:56:00+08:00,154.61,154.63,154.53,154.57,4343.40,2025-07-01 07:56:59.999000+08:00,6.714634e+05,715,1763.93,2.726842e+05,0,32.492389,156.278024,154.497309,155.387667,2025-07-01 07:56:00+08:00,False
2025-07-01 07:57:00+08:00,154.58,154.66,154.58,154.61,11050.65,2025-07-01 07:57:59.999000+08:00,1.708555e+06,979,6743.09,1.042578e+06,0,32.492389,156.278024,154.497309,155.387667,2025-07-01 07:57:00+08:00,False
2025-07-01 07:58:00+08:00,154.61,154.70,154.60,154.70,3998.31,2025-07-01 07:58:59.999000+08:00,6.183070e+05,697,3178.12,4.914714e+05,0,32.492389,156.278024,154.497309,155.387667,2025-07-01 07:58:00+08:00,False
2025-07-01 07:59:00+08:00,154.70,154.82,154.70,154.73,6436.09,2025-07-01 07:59:59.999000+08:00,9.961486e+05,976,3331.40,5.156312e+05,0,32.492389,156.278024,154.497309,155.387667,2025-07-01 07:59:00+08:00,False

In [3]:
t = [{'entry_time': '2025-07-20T01:25:00.349', 'exit_time': '2025-07-20T01:28:18.021', 'is_closed': True, 'realized_pnl': 0.12}, {'entry_time': '2025-07-20T01:20:00.439', 'exit_time': None, 'is_closed': False, 'realized_pnl': None}, {'entry_time': '2025-07-20T01:15:00.381', 'exit_time': '2025-07-20T01:19:39.85', 'is_closed': True, 'realized_pnl': 0.09}, {'entry_time': '2025-07-20T01:10:00.456', 'exit_time': None, 'is_closed': False, 'realized_pnl': None}, {'entry_time': '2025-07-20T01:05:00.325', 'exit_time': None, 'is_closed': False, 'realized_pnl': None}]
t[0]['entry_time']

'2025-07-20T01:25:00.349'