In [8]:
import pandas as pd

In [9]:
data = pd.read_csv('aug_13_test.csv')
# data = data[['open_time','open','high','low','close','volume']]
data = data.rename(columns = {'open_time':'timestamp'})
data.head()

,timestamp,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
0,2025-08-12 18:30:00+08:00,174.51,174.65,174.51,174.65,4956.38,2025-08-12 18:30:59.999000+08:00,8.653146e+05,1783,3288.87,5.741914e+05,0
1,2025-08-12 18:31:00+08:00,174.65,174.69,174.57,174.69,4788.74,2025-08-12 18:31:59.999000+08:00,8.362934e+05,963,3888.02,6.789977e+05,0
2,2025-08-12 18:32:00+08:00,174.70,174.89,174.68,174.89,17756.96,2025-08-12 18:32:59.999000+08:00,3.104116e+06,2288,13106.15,2.291087e+06,0
3,2025-08-12 18:33:00+08:00,174.90,174.99,174.83,174.84,6962.01,2025-08-12 18:33:59.999000+08:00,1.217788e+06,1265,3650.23,6.385239e+05,0
4,2025-08-12 18:34:00+08:00,174.83,174.92,174.82,174.87,8668.09,2025-08-12 18:34:59.999000+08:00,1.515861e+06,1026,7303.24,1.277203e+06,0

In [3]:
data.to_csv('aug_13_test_cleaned.csv')

In [10]:
# june = pd.to_datetime('2025-06-01T00:00:00+08:00')
data['timestamp'] = pd.to_datetime(data['timestamp'])
# june2025 = data[data['timestamp'] >= june]
test = data.set_index('timestamp')
test.head()

,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore
timestamp,,,,,,,,,,,
2025-08-12 18:30:00+08:00,174.51,174.65,174.51,174.65,4956.38,2025-08-12 18:30:59.999000+08:00,8.653146e+05,1783,3288.87,5.741914e+05,0
2025-08-12 18:31:00+08:00,174.65,174.69,174.57,174.69,4788.74,2025-08-12 18:31:59.999000+08:00,8.362934e+05,963,3888.02,6.789977e+05,0
2025-08-12 18:32:00+08:00,174.70,174.89,174.68,174.89,17756.96,2025-08-12 18:32:59.999000+08:00,3.104116e+06,2288,13106.15,2.291087e+06,0
2025-08-12 18:33:00+08:00,174.90,174.99,174.83,174.84,6962.01,2025-08-12 18:33:59.999000+08:00,1.217788e+06,1265,3650.23,6.385239e+05,0
2025-08-12 18:34:00+08:00,174.83,174.92,174.82,174.87,8668.09,2025-08-12 18:34:59.999000+08:00,1.515861e+06,1026,7303.24,1.277203e+06,0

In [11]:
from modules.strategy import simulate_strategy
from modules.indicators import compute_indicators

params = {'sl_pct': 0.005, 'rsi_period': 7, 'bb_std': 2.0, 'sma_period': 30, 'breakeven_buffer': 0.03, 'cooldown_after_loss': True, 'max_concurrent_trades': 3}
test_ind = compute_indicators(test.copy(), params)
test_trades = simulate_strategy(test_ind, params)

2025-08-12 18:35:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.51, previous upper bb: nan, previous lower bb:nan
current close: 174.87, current upper bb: nan, current lower bb:nan
rsi: 0.0
2025-08-12 18:40:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.87, previous upper bb: nan, previous lower bb:nan
current close: 174.51, current upper bb: nan, current lower bb:nan
rsi: 6.08695652174184
2025-08-12 18:45:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.51, previous upper bb: nan, previous lower bb:nan
current close: 174.53, current upper bb: nan, current lower bb:nan
rsi: 47.274206672090976
2025-08-12 18:50:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.53, previous upper bb: nan, previous lower bb:nan
current close: 174.74, current upper bb: nan, current lower bb:nan
rsi: 38.35405435141434
2025-08-12 18:55:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.74, previous upper bb: nan, previous lower bb:nan
current close: 174.65, current upper bb: nan, current lower bb:nan
rsi: 43.34299582041207
2025-08-12 19:00:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.65, previous upper bb: nan, previous lower bb:nan
current close: 174.68, current upper bb: nan, current lower bb:nan
rsi: 47.08972225173191
2025-08-12 19:05:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.68, previous upper bb: nan, previous lower bb:nan
current close: 174.72, current upper bb: nan, current lower bb:nan
rsi: 30.07431527254785
2025-08-12 19:10:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.72, previous upper bb: nan, previous lower bb:nan
current close: 174.5, current upper bb: nan, current lower bb:nan
rsi: 13.168238998916877
2025-08-12 19:15:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.5, previous upper bb: nan, previous lower bb:nan
current close: 173.84, current upper bb: nan, current lower bb:nan
rsi: 46.29006347402907
2025-08-12 19:20:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 173.84, previous upper bb: nan, previous lower bb:nan
current close: 174.47, current upper bb: nan, current lower bb:nan
rsi: 52.04836288665322
2025-08-12 19:25:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.47, previous upper bb: nan, previous lower bb:nan
current close: 174.63, current upper bb: nan, current lower bb:nan
rsi: 52.74375013407567
2025-08-12 19:30:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.63, previous upper bb: nan, previous lower bb:nan
current close: 174.65, current upper bb: nan, current lower bb:nan
rsi: 65.9814758216236
2025-08-12 19:35:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.65, previous upper bb: nan, previous lower bb:nan
current close: 175.11, current upper bb: nan, current lower bb:nan
rsi: 64.15818828120337
2025-08-12 19:40:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.11, previous upper bb: nan, previous lower bb:nan
current close: 175.07, current upper bb: nan, current lower bb:nan
rsi: 47.36223088627223
2025-08-12 19:45:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.07, previous upper bb: nan, previous lower bb:nan
current close: 174.63, current upper bb: nan, current lower bb:nan
rsi: 59.6775653051661
2025-08-12 19:50:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.63, previous upper bb: nan, previous lower bb:nan
current close: 175.07, current upper bb: nan, current lower bb:nan
rsi: 57.535988392406054
2025-08-12 19:55:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.07, previous upper bb: nan, previous lower bb:nan
current close: 175.0, current upper bb: nan, current lower bb:nan
rsi: 61.067597855327264
2025-08-12 20:00:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.0, previous upper bb: nan, previous lower bb:nan
current close: 175.13, current upper bb: nan, current lower bb:nan
rsi: 62.73634961335368
2025-08-12 20:05:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.13, previous upper bb: nan, previous lower bb:nan
current close: 175.2, current upper bb: nan, current lower bb:nan
rsi: 57.03236074150756
2025-08-12 20:10:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.2, previous upper bb: nan, previous lower bb:nan
current close: 175.09, current upper bb: nan, current lower bb:nan
rsi: 51.56291093574307
2025-08-12 20:15:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.09, previous upper bb: nan, previous lower bb:nan
current close: 174.95, current upper bb: nan, current lower bb:nan
rsi: 42.78649448546028
2025-08-12 20:20:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.95, previous upper bb: nan, previous lower bb:nan
current close: 174.73, current upper bb: nan, current lower bb:nan
rsi: 61.062329072301985
2025-08-12 20:25:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 174.73, previous upper bb: nan, previous lower bb:nan
current close: 175.25, current upper bb: nan, current lower bb:nan
rsi: 70.0710459194103
2025-08-12 20:30:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.25, previous upper bb: nan, previous lower bb:nan
current close: 175.68, current upper bb: nan, current lower bb:nan
rsi: 85.10254337418161
2025-08-12 20:35:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 175.68, previous upper bb: nan, previous lower bb:nan
current close: 177.24, current upper bb: nan, current lower bb:nan
rsi: 85.9913418549638
2025-08-12 20:40:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.24, previous upper bb: nan, previous lower bb:nan
current close: 177.43, current upper bb: nan, current lower bb:nan
rsi: 88.93589119991127
2025-08-12 20:45:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.43, previous upper bb: nan, previous lower bb:nan
current close: 178.07, current upper bb: nan, current lower bb:nan
rsi: 89.01874978546421
2025-08-12 20:50:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.07, previous upper bb: nan, previous lower bb:nan
current close: 178.1, current upper bb: nan, current lower bb:nan
rsi: 82.52915229749851
2025-08-12 20:55:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.1, previous upper bb: nan, previous lower bb:nan
current close: 177.9, current upper bb: 177.91085457484775, current lower bb:172.91181209181894
rsi: 80.62436337149877
2025-08-12 21:00:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.9, previous upper bb: 177.91085457484775, previous lower bb:172.91181209181894
current close: 177.86, current upper bb: 178.00035436818297, current lower bb:172.94031229848366
rsi: 48.656351427947705
2025-08-12 21:05:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.86, previous upper bb: 178.00035436818297, previous lower bb:172.94031229848366
current close: 176.64, current upper bb: 178.11174352163488, current lower bb:172.9922564783651
rsi: 54.21203622832517
2025-08-12 21:10:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 176.64, previous upper bb: 178.11174352163488, previous lower bb:172.9922564783651
current close: 176.96, current upper bb: 178.26961988430358, current lower bb:173.0290467823631
rsi: 61.62929657841449
2025-08-12 21:15:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 176.96, previous upper bb: 178.26961988430358, previous lower bb:173.0290467823631
current close: 177.44, current upper bb: 178.43029911839457, current lower bb:173.05570088160542
rsi: 63.19096910811691
2025-08-12 21:20:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.44, previous upper bb: 178.43029911839457, previous lower bb:173.05570088160542
current close: 177.56, current upper bb: 178.60386596941495, current lower bb:173.09213403058502
rsi: 66.64637160057578
2025-08-12 21:25:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.56, previous upper bb: 178.60386596941495, previous lower bb:173.09213403058502
current close: 177.81, current upper bb: 178.79585897095558, current lower bb:173.12547436237776
rsi: 70.30506449637323
2025-08-12 21:30:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.81, previous upper bb: 178.79585897095558, previous lower bb:173.12547436237776
current close: 178.08, current upper bb: 178.9856175776136, current lower bb:173.1677157557197
rsi: 72.02861203291081
2025-08-12 21:35:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.08, previous upper bb: 178.9856175776136, previous lower bb:173.1677157557197
current close: 178.21, current upper bb: 179.13706694954558, current lower bb:173.25826638378769
rsi: 69.49468588386263
2025-08-12 21:40:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.21, previous upper bb: 179.13706694954558, previous lower bb:173.25826638378769
current close: 178.13, current upper bb: 179.12561650311412, current lower bb:173.49038349688587
rsi: 43.97115607767484
2025-08-12 21:45:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.13, previous upper bb: 179.12561650311412, previous lower bb:173.49038349688587
current close: 177.14, current upper bb: 179.10617670263053, current lower bb:173.64582329736947
rsi: 34.43315227230018
2025-08-12 21:50:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.14, previous upper bb: 179.10617670263053, previous lower bb:173.64582329736947
current close: 176.51, current upper bb: 179.09292850582375, current lower bb:173.79240482750959
rsi: 37.638789071281415
2025-08-12 21:55:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 176.51, previous upper bb: 179.09292850582375, previous lower bb:173.79240482750959
current close: 176.62, current upper bb: 179.06473351922233, current lower bb:173.93993314744432
rsi: 34.742461776265515
2025-08-12 22:00:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 176.62, previous upper bb: 179.06473351922233, previous lower bb:173.93993314744432
current close: 176.44, current upper bb: 179.07361372297578, current lower bb:174.05105294369088
rsi: 46.60111188049818
2025-08-12 22:05:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 176.44, previous upper bb: 179.07361372297578, previous lower bb:174.05105294369088
current close: 176.91, current upper bb: 179.1070526916593, current lower bb:174.17561397500737
rsi: 56.90414070089708
2025-08-12 22:10:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 176.91, previous upper bb: 179.1070526916593, previous lower bb:174.17561397500737
current close: 177.44, current upper bb: 179.10515999109285, current lower bb:174.3728400089071
rsi: 58.99406971653863
2025-08-12 22:15:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.44, previous upper bb: 179.10515999109285, previous lower bb:174.3728400089071
current close: 177.57, current upper bb: 179.10456101800602, current lower bb:174.52543898199397
rsi: 53.679264129731
2025-08-12 22:20:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.57, previous upper bb: 179.10456101800602, previous lower bb:174.52543898199397
current close: 177.34, current upper bb: 179.11173420739095, current lower bb:174.69826579260905
rsi: 60.75115985948296
2025-08-12 22:25:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.34, previous upper bb: 179.11173420739095, previous lower bb:174.69826579260905
current close: 177.7, current upper bb: 179.15833735471531, current lower bb:174.8556626452847
rsi: 68.40982099578034
2025-08-12 22:30:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 177.7, previous upper bb: 179.15833735471531, previous lower bb:174.8556626452847
current close: 178.19, current upper bb: 179.22549564182242, current lower bb:175.00983769151094
rsi: 72.49850066200838
2025-08-12 22:35:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.19, previous upper bb: 179.22549564182242, previous lower bb:175.00983769151094
current close: 178.53, current upper bb: 179.24333215765475, current lower bb:175.21533450901185
rsi: 69.54500548452934
2025-08-12 22:40:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.53, previous upper bb: 179.24333215765475, previous lower bb:175.21533450901185
current close: 178.42, current upper bb: 179.27364184240437, current lower bb:175.44769149092892
rsi: 75.60095456527505
2025-08-12 22:45:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.42, previous upper bb: 179.27364184240437, previous lower bb:175.44769149092892
current close: 178.91, current upper bb: 179.2315117907904, current lower bb:175.77248820920957
rsi: 76.52781866231439
2025-08-12 22:50:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.91, previous upper bb: 179.2315117907904, previous lower bb:175.77248820920957
current close: 178.98, current upper bb: 179.30642006326192, current lower bb:175.9802466034047
rsi: 81.77729718051583
2025-08-12 22:55:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 178.98, previous upper bb: 179.30642006326192, previous lower bb:175.9802466034047
current close: 179.49, current upper bb: 179.3980671732314, current lower bb:176.14393282676863
rsi: 81.86827703377034
2025-08-12 23:00:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 179.49, previous upper bb: 179.3980671732314, previous lower bb:176.14393282676863
current close: 179.5, current upper bb: 179.59977252097738, current lower bb:176.1008941456893
rsi: 83.05283809779351
2025-08-12 23:05:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 179.5, previous upper bb: 179.59977252097738, previous lower bb:176.1008941456893
current close: 179.63, current upper bb: 179.74759884555215, current lower bb:176.08573448778117
rsi: 72.87027702513919
2025-08-12 23:10:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 179.63, previous upper bb: 179.74759884555215, previous lower bb:176.08573448778117
current close: 179.42, current upper bb: 179.842634609885, current lower bb:176.06536539011506
rsi: 63.7514421974329
2025-08-12 23:15:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 179.42, previous upper bb: 179.842634609885, previous lower bb:176.06536539011506
current close: 179.2, current upper bb: 180.01467598134903, current lower bb:176.00665735198433
rsi: 74.07421218048614
2025-08-12 23:20:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 179.2, previous upper bb: 180.01467598134903, previous lower bb:176.00665735198433
current close: 179.79, current upper bb: 180.37622244583125, current lower bb:175.8451108875021
rsi: 83.9982239120682
2025-08-12 23:25:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 179.79, previous upper bb: 180.37622244583125, previous lower bb:175.8451108875021
current close: 180.9, current upper bb: 180.75361133606194, current lower bb:175.69172199727134
rsi: 85.75857471672833
2025-08-12 23:30:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 180.9, previous upper bb: 180.75361133606194, previous lower bb:175.69172199727134
current close: 181.21, current upper bb: 181.10912972981865, current lower bb:175.65953693684807
rsi: 87.19047542898092
2025-08-12 23:35:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.21, previous upper bb: 181.10912972981865, previous lower bb:175.65953693684807
current close: 181.48, current upper bb: 181.38963495523015, current lower bb:175.66503171143657
rsi: 78.95766675465417
2025-08-12 23:40:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: True
previous close: 181.48, previous upper bb: 181.38963495523015, previous lower bb:175.66503171143657
current close: 181.24, current upper bb: 181.5768539690704, current lower bb:175.6958126975962
rsi: 63.50800817217569
2025-08-12 23:50:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 180.71, previous upper bb: 181.7942466867502, previous lower bb:175.71241997991652
current close: 181.08, current upper bb: 182.08947439035447, current lower bb:175.6791922763122
rsi: 75.38328275500187
2025-08-12 23:55:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.08, previous upper bb: 182.08947439035447, previous lower bb:175.6791922763122
current close: 181.72, current upper bb: 182.34128085833476, current lower bb:175.66338580833195
rsi: 71.9678824087076
2025-08-13 00:00:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.72, previous upper bb: 182.34128085833476, previous lower bb:175.66338580833195
current close: 181.61, current upper bb: 182.56807359339183, current lower bb:175.66192640660825
rsi: 71.02926054991417
2025-08-13 00:05:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.61, previous upper bb: 182.56807359339183, previous lower bb:175.66192640660825
current close: 181.58, current upper bb: 182.74349265190986, current lower bb:175.69850734809015
rsi: 62.47387331457564
2025-08-13 00:10:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.58, previous upper bb: 182.74349265190986, previous lower bb:175.69850734809015
current close: 181.31, current upper bb: 182.84143920825113, current lower bb:175.85922745841555
rsi: 54.281081924737535
2025-08-13 00:15:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.31, previous upper bb: 182.84143920825113, previous lower bb:175.85922745841555
current close: 181.02, current upper bb: 182.89725652635624, current lower bb:176.1220768069771
rsi: 59.795841465120496
2025-08-13 00:20:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.02, previous upper bb: 182.89725652635624, previous lower bb:176.1220768069771
current close: 181.28, current upper bb: 182.98845095699826, current lower bb:176.3755490430017
rsi: 68.62613983151317
2025-08-13 00:25:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.28, previous upper bb: 182.98845095699826, previous lower bb:176.3755490430017
current close: 181.8, current upper bb: 183.14013318344732, current lower bb:176.64120014988603
rsi: 78.26537395955378
2025-08-13 00:30:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 181.8, previous upper bb: 183.14013318344732, previous lower bb:176.64120014988603
current close: 182.69, current upper bb: 183.44490467965505, current lower bb:176.78642865367829
rsi: 84.2769353429278
2025-08-13 00:35:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 182.69, previous upper bb: 183.44490467965505, previous lower bb:176.78642865367829
current close: 183.66, current upper bb: 183.88915595843474, current lower bb:176.81284404156526
rsi: 87.738879865615
2025-08-13 00:40:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 183.66, previous upper bb: 183.88915595843474, previous lower bb:176.81284404156526
current close: 184.5, current upper bb: 184.28423664073256, current lower bb:176.88576335926746
rsi: 88.03168152355441
2025-08-13 00:45:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 184.5, previous upper bb: 184.28423664073256, previous lower bb:176.88576335926746
current close: 184.57, current upper bb: 184.6082989543218, current lower bb:177.04903437901152
rsi: 88.35608768907596
2025-08-13 00:50:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 184.57, previous upper bb: 184.6082989543218, previous lower bb:177.04903437901152
current close: 184.66, current upper bb: 184.90700807864985, current lower bb:177.21632525468348
rsi: 88.53732957068412
2025-08-13 00:55:00+08:00: LONG SIGNAL: False, SHORT SIGNAL: False
previous close: 184.66, previous upper bb: 184.90700807864985, previous lower bb:177.21632525468348
current close: 184.7, current upper bb: 185.20083233279712, current lower bb:177.3611676672029

In [12]:
pd.DataFrame(test_trades)

,entry_time,exit_time,type,entry_price,exit_price,pnl,reason
0,2025-08-12 23:40:00+08:00,2025-08-12 23:42:00+08:00,short,181.04,180.913272,2.8,sl
1,2025-08-13 05:50:00+08:00,2025-08-13 05:51:00+08:00,short,192.83,192.695019,2.8,sl
2,2025-08-13 08:50:00+08:00,2025-08-13 08:51:00+08:00,short,194.17,194.034081,2.8,sl
3,2025-08-13 11:10:00+08:00,2025-08-13 11:14:00+08:00,short,196.90,197.884500,-20.0,sl
4,2025-08-13 13:40:00+08:00,2025-08-13 13:51:00+08:00,long,197.78,196.791100,-20.0,sl
5,2025-08-13 14:10:00+08:00,2025-08-13 14:15:00+08:00,long,196.55,196.687585,2.8,sl

In [8]:
julytrades = pd.DataFrame(july_trades) 
julytrades.to_csv('july_trades.csv')

In [9]:
test_ind.to_csv('aug_13_test_ind.csv')

In [3]:
t = [{'entry_time': '2025-07-20T01:25:00.349', 'exit_time': '2025-07-20T01:28:18.021', 'is_closed': True, 'realized_pnl': 0.12}, {'entry_time': '2025-07-20T01:20:00.439', 'exit_time': None, 'is_closed': False, 'realized_pnl': None}, {'entry_time': '2025-07-20T01:15:00.381', 'exit_time': '2025-07-20T01:19:39.85', 'is_closed': True, 'realized_pnl': 0.09}, {'entry_time': '2025-07-20T01:10:00.456', 'exit_time': None, 'is_closed': False, 'realized_pnl': None}, {'entry_time': '2025-07-20T01:05:00.325', 'exit_time': None, 'is_closed': False, 'realized_pnl': None}]
t[0]['entry_time']

'2025-07-20T01:25:00.349'